#
# Netlify build and functions configuration
#

[build]
  # The directory where Netlify should look for your functions
  functions = "netlify/functions"
  # You can specify a build command here if needed, e.g., 'npm run build'
  command = "npm install"

#
# Netlify redirects to route requests to the correct function endpoint
#

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/webhook"
  status = 200
