name = "data-user-bot"
main = "index.js"
compatibility_date = "2024-09-21"

[vars]
BOT_TOKEN = "8272634262:AAHXUYw_Q-0fwuyFAc5j6ntgtZHt3VyWCOM"
IMGBB_API_KEY = "7b98d38c418169cf635290b4a31f8e95"

[[d1_databases]]
binding = "DB"
database_name = "data"
database_id = "f86a77cd-31f4-4730-8ed3-32945b46d58c"
