name = "syrian-martyrs-bot"
main = "src/index.js"
compatibility_date = "2023-01-01"

[vars]
BOT_TOKEN = "8272634262:AAHXUYw_Q-0fwuyFAc5j6ntgtZHt3VyWCOM"
IMGBB_API_KEY = "7b98d38c418169cf635290b4a31f8e95"

[[kv_namespaces]]
binding = "BOT_DATA"
id = "69971ebf8d584ca598400aea3d8a477d"
